FROM registry.fedoraproject.org/fedora:latest

RUN set -eux pipefail; dnf -y upgrade; dnf -y install pipx git-core

COPY . /src/
WORKDIR /src/

RUN set -eux pipefail; pipx install .
EXPOSE 8000
ENTRYPOINT app
HEALTHCHECK --interval=5s --timeout=1s CMD curl http://localhost:8000/hook
